services:
  - type: web
    name: cloudvault-api
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./cloudvault.db
      - key: JWT_SECRET
        generateValue: true
      - key: STORAGE_MODE
        value: local
      - key: CORS_ORIGINS
        value: '["https://frontend-beige-seven-9zau5j5m3v.vercel.app","http://localhost:5173"]'
